### ISSUE TITLE
Error: The model does not have a valid input feature of type image

### ISSUE THREAD

**Issue by choas** [kingreza/SeeFood#1]
guard let model = try? VNCoreMLModel(for: food().model) throws an error.

Looking at the (downloaded) food.mlmodel file it has a MultiArray as input (instead of Image e.g. InceptionV3).

**Comment by eugenpirogoff** [comment]
After removing and adding the model again (I needed multiple attempts) the class is now generated correctly and can be instantiated

**Comment by eugenpirogoff** [comment]
@choas 

You seem to be right about the model.

```
systemgroup.com.apple.configurationprofiles
2017-07-26 11:44:01.784907+0200 SeeFood[1091:348632] [MC] Reading from public effective user settings.
2017-07-26 11:44:03.313515+0200 SeeFood[1091:348815] Error: The model does not have a valid input feature of type image
fatal error: file /Users/eugen/Downloads/SeeFood-master/SeeFood/ViewController.swift, line 78
2017-07-26 11:44:03.336463+0200 SeeFood[1091:348815] fatal error: file /Users/eugen/Downloads/SeeFood-master/SeeFood/ViewController.swift, line 78
(lldb) ```

**Comment by kingreza** [comment]
What version of xcode are you running?

**Comment by eugenpirogoff** [comment]
@kingreza 

new Beta 4 (9M189t)

**Comment by choas** [comment]
I've tried it with Version 9.0 beta 3 (9M174d) and then also with Version 9.0 beta 4 (9M189t). Both causes this error.

**Comment by kingreza** [comment]
@eugenpirogoff  By your comment I'm assuming you were able to import the model successfully?  Was the input defined as Image or MultiArray? Were you able to get the project up and running?

**Comment by eugenpirogoff** [comment]
@kingreza 

Yep the import seems fine and it is MultiArray, both Input(data) and Output(prob). It compiles and crashes with the error log pasted above after asking for camera permission and showing the view controller.

**Comment by hpsoar** [comment]
same problem here. @kingreza

**Comment by kingreza** [comment]
I can't recreate this issue on my machine. I have rebuild the model and uploaded it [here](https://s3.amazonaws.com/pixpit/coreml/food.mlmodel). If that doesn't work I have uploaded the [Caffe model](https://s3.amazonaws.com/pixpit/coreml/trained_model.tar.gz) here. You could try and convert it using coremltool and see if that works. 

If none of that works I just finished writing a guide on how to train, convert and integrate your own model by building SeeFood from the ground up. You could try that by going [here](http://reza.codes/2017-07-29/how-to-train-your-own-dataset-for-coreml/).

Let me know if any of this works for you guys

**Comment by choas** [comment]
The newly uploaded model is working (shows Image as input).
I'm also able - with the help of your nicely written guide - to convert the Caffe model to a CoreML model (shows also Image as input).
