### ISSUE TITLE
Use of unresolved identifier 'food'

### ISSUE THREAD

**Issue by hssdx** [kingreza/SeeFood#2]
In ` ViewController.swift `  line: 74

compiler error:Use of unresolved identifier 'food'

**Comment by kingreza** [comment]
You need to download and import the food model. It's too big to be included in the repo. For more info read through this http://reza.codes/2017-07-29/how-to-train-your-own-dataset-for-coreml/#integrate

**Comment by douglastaquary** [comment]
When i do import the food model to `xcode 9 beta 5`, the same error remains in `ViewController.swif` line `74`. Any tips?. The model is there, but not work.

**Comment by kingreza** [comment]
I rebuilt the project using `beta 5` using the model here: https://s3.amazonaws.com/pixpit/coreml/food.mlmodel
It works on my end, go through the steps highlighted in the post above.

**Comment by hssdx** [comment]
@kingreza  Thank for you answer, I solved it, because my xcode9 does not automatically import the `food.mlmodel`

**Comment by hssdx** [comment]
XCode 9 needs to manually linke mlmodel after dragging to Project.

**Comment by douglastaquary** [comment]
@hssdx how "manually linke" mlmodel in xcode9? 🤔 Only drag and drop isn't solve?

**Comment by hssdx** [comment]
@douglastaquary  yep, I don't know why, maybe my xcode has broken. Finally I drag it to `TARGETS - Build Phases - Compile Sources` it worked.
I guess this is a xcode9's bug.
